# Generated by Django 2.2 on 2019-04-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api', '0003_auto_20190405_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitching',
            old_name='bapp',
            new_name='baopp',
        ),
    ]
